apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: api
  namespace: innovalia
spec:
  parentRefs:
  - name: innovalia-external
    namespace: gateway
  hostnames:
  - innovalia-uc2-api.sedimark.work
  rules:
  - matches:
    - path: { type: PathPrefix, value: / }
    backendRefs:
    - name: api
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: frontend
  namespace: innovalia
spec:
  parentRefs:
  - name: innovalia-external
    namespace: gateway
  hostnames:
  - innovalia-uc2.sedimark.work
  rules:
  - matches:
    - path: { type: PathPrefix, value: / }
    backendRefs:
    - name: frontend
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: control-panel
  namespace: innovalia
spec:
  parentRefs:
  - name: innovalia-external
    namespace: gateway
  hostnames:
  - innovalia-uc2-panel.sedimark.work
  rules:
  - matches:
    - path: { type: PathPrefix, value: / }
    backendRefs:
    - name: control-panel
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: flower
  namespace: innovalia
spec:
  parentRefs:
  - name: innovalia-external
    namespace: gateway
  hostnames:
  - innovalia-uc2-flower.sedimark.work
  rules:
  - matches:
    - path: { type: PathPrefix, value: / }
    backendRefs:
    - name: flower
      port: 80
